"""empty message

Revision ID: 832dd17dbcb8
Revises: 6a916fd43a61
Create Date: 2022-02-05 00:33:49.658584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832dd17dbcb8'
down_revision = '6a916fd43a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
